version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./prisma/generate-test-data.sql:/docker-entrypoint-initdb.d/generate-test-data.sql

  service:
    build: .
    environment:
      DATABASE_URL: postgres://devuser:devpassword@db:5432/devdb
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
